name: "Nuclei Action"
description: "Nuclei is a fast and customisable vulnerability scanner based on simple YAML based DSL"

inputs:
  url:
    description: URL to scan
    required: true
  output:
    description: "File to save output result"
    required: false
    default: "nuclei.log"
  user-agent:
    description: "Set a User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

runs:
  using: "composite"
  steps:
    - run: |
        if ! [ -x "$(command -v nuclei)" ]; then
          wget -q https://github.com/projectdiscovery/nuclei/releases/download/v2.9.15/nuclei_2.9.15_linux_amd64.zip
          unzip nuclei_2.9.15_linux_amd64.zip
          mkdir -p $HOME/.local/bin
          mv nuclei $HOME/.local/bin/
        fi
      shell: bash

    - run: |
        $HOME/.local/bin/nuclei \
          -target ${{ inputs.url }} \
          -json-export ${{ inputs.output }} \
          -header "User-Agent: ${{ inputs.user-agent }}"
      shell: bash
